### ISSUE TITLE
Widening Gnome-terminal corrupts screen

### ISSUE THREAD

**Issue by penttila** [linuxmint/cinnamon-desktop#101]
1) Pull the right edge of gnome-terminal to an 'extreme' length by the mouse
2) When its size extends the 251 width a kind of 'shadow' frame appears around the window's normal frame which corrupts the desktop screen!
3) This always happens and 'undo-able' by decreasing the window size
![screenshot](https://user-images.githubusercontent.com/8037522/33927982-78463d38-dfe4-11e7-966a-5f394342acfe.png)

(I also reported this bug on Launchpad as #1737888)

Gnome-terminal: 3.18.3

System:    Host: afo Kernel: 4.10.0-42-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.6.6 (Gtk 2.24.30) dm: mdm Distro: Linux Mint 18.3 Sylvia
Machine:   Mobo: Gigabyte model: G31M-ES2L v: x.x Bios: Award v: FG date: 02/24/2010
CPU:       Dual core Pentium E5500 (-MCP-) cache: 2048 KB
           flags: (lm nx sse sse2 sse3 ssse3 vmx) bmips: 11200
           clock speeds: min/max: 1200/2800 MHz 1: 1200 MHz 2: 1200 MHz
Graphics:  Card: Intel 82G33/G31 Express Integrated Graphics Controller
           bus-ID: 00:02.0 chip-ID: 8086:29c2
           Display Server: X.Org 1.18.4 drivers: intel (unloaded: fbdev,vesa)
           Resolution: 1280x1024@60.02hz
           GLX Renderer: Mesa DRI Intel G33 GLX Version: 1.4 Mesa 17.0.7 Direct Rendering: Yes

**Comment by leigh123linux** [comment]
You have filed the issue against the wrong package, muffin draws the window decoration.

https://github.com/linuxmint/muffin/issues

**Comment by penttila** [comment]
OK, thanks. I moved it to https://github.com/linuxmint/muffin/issues.
