### ISSUE TITLE
[ Enhancement ] [ Bug ] Menu links and Launcher links to laptops NTFS drives don't work

### ISSUE THREAD

**Issue by Tsoccerguy3** [linuxmint/cinnamon-desktop#102]
Product
http://www.canadacomputers.com/product_info.php?cPath=710_577_1199&item_id=114634

My setup works great with exception to the following .
I Wiped SSD and 1 TB Hard Drive , clean installations on UEFI/GPT-based hard drive partitions
SSD partition 64 gig Win10 NTFS , 64 gigs Mint 18.3  with 2gig swap / 20 gig root EXT4  / 42 gig home EXT4
1 TB Hard drive GPT NTFS used as Data Drive
Environment : Dual boot Mint 18.3 Cinnamon and Win 10 x64

Manually launching programs on extra internal or external drives work fine !
Adding programs to the Mint Menu , that are on the 1 TB GPT NTFS  Data drive , do not launch . The links that are created by the Mint Menu or the desktop launcher , do not take into consideration a dual boot situation where a larger data drive on a laptop will be shared by windows 10 and Mint . Also creating a desktop launcher to the 1 TB data drive or a manual link on the desktop do not work . 

The links created by Mint should take into consideration the shared security on a shared data drive , be it internal or a USB / eSATA external drive .

**Comment by leigh123linux** [comment]
Your report doesn't make sense, cinnamon-desktop code isn't responsible for the desktop or menu.

**Comment by Tsoccerguy3** [comment]
It would help if you could point me to the code that is responsible for menu and link creation . Your comment does nothing to address the issue and is no help

**Comment by leigh123linux** [comment]
@Tsoccerguy3  Your issue is because your using a  crappy windoze file system, you will need to mount it with execute perms.

https://askubuntu.com/questions/245154/how-to-get-permissions-to-execute-programs-from-ntfs-hard-drive
