### ISSUE TITLE
Desktop freezes on HDMI connection

### ISSUE THREAD

**Issue by ambs** [linuxmint/cinnamon-desktop#110]
Hi.
I know this might not be a cinnamon desktop issue, but my hope is that you can help me finding out where to report this bug.
Basically, sometimes, when I connect an external monitor to my linux, using HDMI, it works pretty well. Some other times, the screen freezes, and only the mouse moves. Keyboard does nothing, and can't even change from X to the text consoles.
Thanks
Alberto

**Comment by ItzSwirlz** [comment]
Does this still occur?

**Comment by ambs** [comment]
No. Can be closed. Thanks!
