### ISSUE TITLE
Fix desktop.session schema for non-systemd platforms

### ISSUE THREAD

**Issue by nbyouri** [linuxmint/cinnamon-desktop#117]
For NetBSD and other non-systemd platforms, cinnamon-session crashes in various ways because the org.cinnamon.desktop.session keys:

- session-manager-uses-logind
- settings-daemon-uses-logind

Are unconditionally set to true regardless of whether the system actually uses systemd or not. For NetBSD it's easy I just patched the dconf file to set it to false but this project would benefit from a check and replace at configure time with meson since some linux distributions don't use systemd.

**Comment by leigh123linux** [comment]
Use a gschema override to set it.
