### ISSUE TITLE
rename package: libcinnamon-desktop0 -> libcinnamon-desktop4

### ISSUE THREAD

**Issue by darealshinji** [linuxmint/cinnamon-desktop#12]
Library packages must be named according to the lib's soversion number.

**Comment by GLolol** [comment]
This is done in the latest master, but there are still issues upgrading from `libcinnamon-desktop0` to `libcinnamon-desktop4` (linuxmint/nemo#921).

**Comment by darealshinji** [comment]
You could try `Provides: libcinnamon-desktop0` and/or `Replaces: libcinnamon-desktop0` and see if that fixes it.
