### ISSUE TITLE
When will the new Debian?

### ISSUE THREAD

**Issue by xzj8b3** [linuxmint/cinnamon-desktop#136]
Ich möchte von Fedora auf Mint Debian migrieren, das stabiler ist und Cinnamon macht es nichts aus, sehr reaktionsschnell und scheint nicht zu viele Ressourcen zu verbrauchen.

Ich habe gelesen, dass ein neues "LMDE Debby" veröffentlicht wird. Aber wann?

**Comment by NikoKrause** [comment]
Das ist kein Cinnamon-Dektop Problem.

Du kannst ja LMDE3 installieren und upgraden sobald LMDE4 rauskommt.
Upgrade ging bisher auch und ich würde vermuten, dass es wieder so ähnlich wie von LMDE2 auf LMDE3 aussehen wird: https://blog.linuxmint.com/?s=LMDE&submit=Search

**Comment by xzj8b3** [comment]
> Das ist kein Cinnamon-Dektop Problem.
> 
> Du kannst ja LMDE3 installieren und upgraden sobald LMDE4 rauskommt.
> Upgrade ging bisher auch und ich würde vermuten, dass es wieder so ähnlich wie von LMDE2 auf LMDE3 aussehen wird: https://blog.linuxmint.com/?s=LMDE&submit=Search

The new Iso???????

**Comment by NikoKrause** [comment]
There's no iso for LMDE4, because LMDE4 hasn't been released yet.
Your only option for LMDE right now is to use LMDE3.

**Comment by NikoKrause** [comment]
http://mirror.bauhuette.fh-aachen.de/linuxmint-cd/debian/lmde-3-201808-cinnamon-64bit.iso
