### ISSUE TITLE
"Ctrl+Shift+E" interrupts following keyboard inputs

### ISSUE THREAD

**Issue by onequid** [linuxmint/cinnamon-desktop#139]
I am not sure if this is the right place to post this issue as I have not tried to reproduced this on any other distro with cinnamons.

Steps to reproduce:
1. When typing, press CTRL+SHIFT+E,
2. Try to input some other words, and it was not as expected.

In some input areas `Ctrl+Shift+E` would interrupts following keyboard inputs.
It happened in following places so far:
- in the search area of the menu
- entering address in firefox
- gnome-terminal

It did not happen in hexchat(the only place where the reproducing failed).
And I also found that after press the **ENTER** key, the keyboard works again.
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 19.2 Tina
Release:	19.2
Codename:	tina
```
The theme used is Mint-Y-Dark. And I reproduced this with theme Cinnamon
Thank you for your attention.

I also tested a live image on the VM, it was with an underlined `e` and following inputs(the undelined e and the following inputs are hidden on my machine). **CTRL+SHIFT+E** is used to enter emoji.

It is weird that I do not see it configured in `ibus-setup`. And I get nothing with the cmd below:
``` bash
$ gsettings get org.freedesktop.ibus.panel.emoji hotkey
@as []
```

**Comment by OneQuid** [comment]
Found it was caused by "fcitx". And it was just solved.

**Comment by onequid** [comment]
I tried to add the following lines to ~/.profile
```
export GTK_IM_MODULE=xim
export QT_IM_MODULE=xim
export XMODIFIERS="@im=fcitx"
```
This stops mapping **CTRL+SHIFT+E** to entering emoji (and it stops keybinding CTRL+SHIFT+U for entering unicode as well)

However after doing so, when typing in Chinese with some applications, say, LibreOffice Writer and VSCode, it occasionally input some letters directly without going though the Input Method.
For example, when I try to enter something like
![input-test-wanted](https://user-images.githubusercontent.com/49135017/70974335-77a19f80-20e2-11ea-8058-aca4a21fbf42.png)


It would occasionally behave like
![input-test-occasional](https://user-images.githubusercontent.com/49135017/70974352-7cfeea00-20e2-11ea-8d11-8de336932ec3.png)

**Is there any other ways to unset **CTRL+SHIFT+E** keybinding?** or **fix the occasionally direct inputing**?
