### ISSUE TITLE
increase hotcorner functionality

### ISSUE THREAD

**Issue by sahilguleri** [linuxmint/cinnamon-desktop#14]
i am very impressed by the way gnome has introduced message tray at bottom of screen.
it would be great if Linux mint has same functionality but this messge tray would
pop up at top of screen if we hit a hotcorner. we can use space more eficiently like adding message etc

![dd8e7c60-ee74-11e3-95ab-47a083effae0](https://cloud.githubusercontent.com/assets/7669448/3218616/b0c2d482-efec-11e3-9252-39b518dc5540.png)

![0c2b3a04-ee75-11e3-8f1b-dae3225aaf78](https://cloud.githubusercontent.com/assets/7669448/3218623/c1a4ea06-efec-11e3-8c44-bd34954a02ba.png)

**Comment by JosephMcc** [comment]
Even gnome users hated that message tray thing and it was mostly redesigned. This would be better here anyway: https://github.com/linuxmint/Cinnamon
