### ISSUE TITLE
Sound applet problem with Control Players option enabled...

### ISSUE THREAD

**Issue by invexx** [linuxmint/cinnamon-desktop#143]
I'm not playing any music but I can't remove 'Chromium Stopped'.
I don't even have Chromium installed.

![Selection_840](https://user-images.githubusercontent.com/26446962/72669199-43284880-39ec-11ea-9c6c-416f86265268.png)

**Comment by leigh123linux** [comment]
Use the template next time.

**Comment by brownsr** [comment]
Any video on any browser that uses chromium as a Base can show this, my opera browser does that for example.

**Comment by invexx** [comment]
Thank you for the explanation.
But shouldn't it disappear when the browser is closed?
