### ISSUE TITLE
gnome-rr scale fix leads to screen flickering on external monitor

### ISSUE THREAD

**Issue by vladimir-didenko** [linuxmint/cinnamon-desktop#151]
Upgrade to cinnamon-desktop 4.6.2 with fix for gnome-rr scale leads to Cinnamon screen flickering (it is almost unusable) when external monitor is attached. 

Steps to reproduce:
1. Attach external monitor to laptop
2. Login into Cinnamon

After login screen starts flickering. It is interesting that this issue doesn't happen when I login into Cinnamon first and then attach external monitor.

**Comment by mtwebster** [comment]
This should be fixed (see linked issue)
