### ISSUE TITLE
Color manager doesn't work on Mint 20 Cinnamon ( upgraded from Mint 19.3 )

### ISSUE THREAD

**Issue by Leopard1907** [linuxmint/cinnamon-desktop#153]
Hi. Basically it doesn't recognize my monitor anymore and due to that i can't apply any ICC profiles and colors are all washed out.

https://bugs.launchpad.net/ubuntu/+source/ubuntu-release-upgrader/+bug/1861756

Seems like that was also an issue on Ubuntu base with upgrades but report says " Fix released " however it is broken on Mint.

**Comment by leigh123linux** [comment]
Duplicate of #8751
