### ISSUE TITLE
Pinned application icon open but unfocused indistinguishable from not open

### ISSUE THREAD

**Issue by php4fan** [linuxmint/cinnamon-desktop#155]
**Steps to reproduce:**

- pin Gedit to the panel (could use any other application)

Case 1:

- open Gedit
- minimize it or give focus to some other window

Case 2:

- don't open Gedit, and if you have any Gedit windows open, close them

**Expected behavior:**

Gedit's icon in Panel should look different in case 1 and case 2. You should be able to tell whether you have any window of that application open or not.

**Observed behavior:**

there's no difference whatsoever between case 1 and 2. You can tell if the window corresponding to a panel icon is currently focused, but if it isn't, you can't tell whether it has any windows open or not.

**Comment by JosephMcc** [comment]
When filing an issue like this please state what theme you are using. I don't see this issue with the Mint-Y themes. Any application with an open window has an indicator. So does the one with the current focus.

**Comment by php4fan** [comment]
Here's my Themes settings, I hope this is what you are asking. I never changed any.

![image](https://user-images.githubusercontent.com/13969584/87848910-b865cf00-c8e4-11ea-9bb8-91d102929788.png)

I have tried all the options for the Desktop theme and I observe the issue with all of them. I don't know what the "?" was supposed to mean, but it seems like Cinnamon is the one that was initially selected, at least it's the only one that looks the same.

I have tried changing "Window borders", "icons" and "Controls" and none seems to fix the issue, though I haven't tried all the possible combinations.

Now I see that in Tweaks -> Appearence -> Themes there is a setting for an "Applications" theme that isn't listed in the System settings. I have Yaru selected; I have also tried a few others with no luck.

Here's a screenshot:

![image](https://user-images.githubusercontent.com/13969584/87849172-c3216380-c8e6-11ea-864f-10469f001142.png)


Gedit and Gimp are open, FileZilla isn't (all of these and Telegram are pinned).

**Comment by php4fan** [comment]
OMG now I see it. It's just poorly designed.

Those subtle vertical lines around an icon are the indicator that it's open 🤦

I thought those were just separators between the icons. (actually I'm not quite sure they were there before I switched themes forth and back but I'll assume I hadn't seen them)

You can actually tell which ones are open and which ones are not, but it requires a close and careful look, especially if you happen to have an alternating sequence of open and unopen icons.
