### ISSUE TITLE
Fix the sorting triangles. Don't make the same mistake as Gnome

### ISSUE THREAD

**Issue by php4fan** [linuxmint/cinnamon-desktop#156]
I decided to try Cinnamon because I'm sick of Gnome's drift towards madness, their continuous idiotic design decisions, their active commitment to making Gnome worse and making their users' life miserable. Because these seemed to be the same reasons that motivated Cinnamon's creation as a fork of Gnome, I trust the community of developers behind Cinnamon to have better judgment than that of the one behind Gnome. That is, to have any judgment at all.

So, I'm a bit disappointed to see that the convetion of sorting triangle icons (often wrongly called arrows) is not fixed in Cinnamon.

The issue is described here:
https://bugs.launchpad.net/ubuntu/+source/meta-gnome3/+bug/1887414

I hoped Cinnamon would get this right. Please fix the mistake you evidently inherited from Gnome.

**Comment by php4fan** [comment]
In a nutshell (not my work):

![image](https://user-images.githubusercontent.com/13969584/87549357-00e77780-c6ae-11ea-8d97-eaa035eead0b.png)

**Comment by JosephMcc** [comment]
I'm closing this for a couple reasons. One, I don't think this is the place to for bashing on other projects. Weather or not you are a fan. The other is because I don't think we have any intention of patching a ton of applications or gtk itself to change this behaviour.
