### ISSUE TITLE
Shift+PrintScreen shortcut stopped working

### ISSUE THREAD

**Issue by php4fan** [linuxmint/cinnamon-desktop#157]
I took a cropped screenshot by hitting Shift+PrintScreen and  then dragging to select the area of the screen. This took a screenshot of the selected area just like it used to in Gnome.

Then I tried to do the exact same thing again, and Shift+PrintScreen does nothing.

**Comment by mtwebster** [comment]
What distro and what version of gnome-screenshot?  If you hammer shift-printscreen a bunch of times does it eventually work? (There's a fix for this in Mint, is why I ask)

**Comment by php4fan** [comment]
Sorry, I'm using Ubuntu 20.04. gnome-screenshot 3.36.0

**Comment by mtwebster** [comment]
Try this one: http://packages.linuxmint.com/pool/upstream/g/gnome-screenshot/gnome-screenshot_3.36.0-linuxmint1_amd64.deb

**Comment by php4fan** [comment]
How will that interfere with package management?

Usually I install everything throug apt and always install the automatic updates.

**Comment by mtwebster** [comment]
It's a fairly independent package so it should be fine, though I can't ever be 100% certain.  Worst case you can do `apt-get install -f` and it would likely remove that and add the original version.

I had submitted a patch for this but it wasn't accepted - I think they've rewritten things substantially so it was invalid.  I don't think there's much impetus to fix this issue because for gnome-shell (ubuntu's default now) it's not an issue - they interact with gnome-shell itself to take screenshots, whereas we rely on a fallback mechanism (as would any other non-gnome-shell desktop).

**Comment by php4fan** [comment]
Cool! That also fixes this:
https://bugs.launchpad.net/ubuntu/+source/gnome-screenshot/+bug/1887240

Please never change that

**Comment by SparkyBluefang** [comment]
I also have this issue on Gentoo with gnome-screenshot 3.36.0. It seems to be somehow related to the way Cinnamon is invoking the command. If I open a terminal and directly invoke `gnome-screenshot --area` it is functional.
```
sparky@Lappy486 ~ $ gnome-screenshot --area
** Message: 09:33:08.785: Unable to select area using GNOME Shell's builtin screenshot interface, resorting to fallback X11.
** Message: 09:33:10.536: Unable to use GNOME Shell's builtin screenshot interface, resorting to fallback X11.
sparky@Lappy486 ~ $ 
```
But Cinnamon's invocation crashes.
```
** Message: 09:34:03.840: Unable to select area using GNOME Shell's builtin screenshot interface, resorting to fallback X11.
** Message: 09:34:04.044: Unable to use GNOME Shell's builtin screenshot interface, resorting to fallback X11.

(gnome-screenshot:22231): Gdk-CRITICAL **: 09:34:04.045: gdk_pixbuf_get_from_surface: assertion 'width > 0 && height > 0' failed

(gnome-screenshot:22231): Gtk-CRITICAL **: 09:34:04.059: gtk_window_resize: assertion 'width > 0' failed

** (gnome-screenshot:22231): CRITICAL **: 09:34:04.060: Unable to capture a screenshot of any window
```
All of the other gnome-screenshot commands are functional except `--area` and `--area --clipboard`.

Maybe a work-around would be to force the area commands to be interactive with `--interactive`?

**Comment by ItzSwirlz** [comment]
Oh, well I found this too in Cinnnamon 4.8.8, on Ubuntu C.R 20.04.

**Comment by mtwebster** [comment]
Please read: https://github.com/linuxmint/cinnamon/issues/3981#issuecomment-733899265
