### ISSUE TITLE
GTK fork

### ISSUE THREAD

**Issue by smnthermes** [linuxmint/cinnamon-desktop#165]
GTK 4 won't give place for a traditional desktop. Therefore, Cinnamon, MATE and Xfce should unite and develop a GTK fork.

**Comment by leigh123linux** [comment]
GTK3 will be around for many years to come.

**Comment by sc0w** [comment]
I am working in a gtk fork since some time ago:

https://github.com/cafe-desktop/ctk

I ported some applications and it just works.

**Comment by ItzSwirlz** [comment]
I don't want to start a toolkit war. Sure, Gtk is not the best toolkit. It's not as new as things like Flutter (which I primarily use now) is. But GTK is still well maintained, and it will be for a while. I wouldn't recommend starting a new project on it (use newer toolkits) but if you already have a GTK project, keep maintaining it. It is good at what its purpose is.

Also, unless there is a high demand, ctk won't be packaged by distros. But, I hope you enjoy experimenting and having fun on your ctk journey @sc0w :)

**Comment by leigh123linux** [comment]
LOL,  CTK has never done a proper versioned release.

https://github.com/commontk/CTK

Also GTK3 is much more stable since gnome moved on to GTK4.

**Comment by jelabarre59** [comment]
So how do we get our Title Bars back?  How do we get theming back (especially for Window Borders and Titles)?   Scrollbar arrows that don't require all sorts of hacks to get them back and functional?

**Comment by leigh123linux** [comment]
> So how do we get our Title Bars back? How do we get theming back (especially for Window Borders and Titles)? Scrollbar arrows that don't require all sorts of hacks to get them back and functional?

You don't unless you use older versions of muffin/cinnamon

**Comment by jelabarre59** [comment]
So thus why I think we need to abandon GTK in favor of  libraries that aren't beholden to the GNOME project.   That or fork Cinnamon and port it over to CTK.

**Comment by sc0w** [comment]
> LOL, CTK has never done a proper versioned release.
> 
> https://github.com/commontk/CTK
> 
> Also GTK3 is much more stable since gnome moved on to GTK4.

https://github.com/commontk/CTK <- this is not gtk fork (it is another project)

the gtk fork which I am working is here:

https://github.com/cafe-desktop/ctk

more some projects if you are interested:

vte fork using ctk: https://github.com/cafe-desktop/bte

gtksourceview fork using ctk: https://github.com/cafe-desktop/ctksourceview

libpeas fork using ctk: https://github.com/cafe-desktop/libbean

libcanberra fork using ctk: https://github.com/cafe-desktop/libkanberra

libwnck fork using ctk: https://github.com/cafe-desktop/libvnck

The other repos inside CAFE desktop (not finished yet) https://github.com/orgs/cafe-desktop are just MATE repos forks with ctk

btw, a ctk theme installed is needed to improve the look
