### ISSUE TITLE
Default white-background black-text terminal is a bad idea

### ISSUE THREAD

**Issue by teo1978** [linuxmint/cinnamon-desktop#167]
I know this can be configured in the Terminal settings, but I usually expect out-of-the-box defaults to be practical, if not pretty, so you should consider this.

No matter what theme one is using for their desktop and windows (light, dark, or anything in-bewteen), it is generally a bad idea to use a white(ish)  background and black(ish) text color for a terminal.

A lot of the commands and programs that are commonly used in terminal (e.g. ls or vim) use default colourings that are designed to work well on a black or very dark background.

So, if you have a fresh install of Cinnamon, and you never tweaked any preferences for any of the programs that you run in your terminal, what happens is:
- you open a terminal, run a "ls" command, or edit some file with vim, and immediately you get unreadable bright-yellow and bright-cyan coloured text (anything that is highlighted in colours) over a white (or almost white) background.

**Comment by ItzSwirlz** [comment]
I think this is something the OS devs can do, I don't think this has to do with Cinnamon

**Comment by JosephMcc** [comment]
We don't know which OS you are running Cinnamon on since you don't tell us but that is not the case in a default Mint install. But the other poster is correct. This isn't done by Cinnamon.
