### ISSUE TITLE
Number of workspaces constantly getting reset

### ISSUE THREAD

**Issue by knochenhans** [linuxmint/cinnamon-desktop#176]
Hi, I’ve set my number of workspaces via ```gsettings set org.cinnamon.desktop.wm.preferences num-workspaces 10``` but the option keeps getting reset, sometimes after waking up the system from suspend and generally after restarting cinnamon. Is there any way to keep this number fixed at all times?

**Comment by clefebvre** [comment]
Ctrl+Alt+Up, create as many workspaces as you want. You're not supposed to set this in dconf directly.

**Comment by knochenhans** [comment]
I’m working with a fixed number of workspaces for specific applications and tasks using Devilspie, so it would be nice to have a way to fix the number of workspaces. I don’t want to touch that my workspace setup anymore after that. Is there any way to do that with cinnamon?

**Comment by clefebvre** [comment]
Cinnamon will keep the workspaces you created. That's persistent.

What happens here is that you're not creating them, you're just hacking one of the values it reads... you'd only do that if you wanted to change the default for everybody, and you'd have not only to change that number but also set names and all. If you're just using Cinnamon, create the workspaces using Cinnamon. You'll only have to do it once.

**Comment by knochenhans** [comment]
Okay, thanks for explaining. Got the tip from https://wiki.archlinux.org/index.php/Cinnamon but seems that info wasn’t reliable.

**Comment by clefebvre** [comment]
No problem. If you wanted to override the default workspace number and names, you'd probably want to set an array of names in `org.cinnamon.desktop.wm.preferences workspace-names` as well, using a gsettings override.
