### ISSUE TITLE
Right clicking on apps and selecting "Run with NVIDIA GPU" not working

### ISSUE THREAD

**Issue by sathvik987** [linuxmint/cinnamon-desktop#190]
* Cinnamon version (4.8.6)
 * Distribution - (Linux Mint 20.1)
 * Graphics hardware - mx150 *and* driver used - nvidia-driver-460
 * 64 bit
 
**Issue**

I am running Linux Mint 20.1 Cinnamon with 5.4.0-70-generic kernel and nvidia-driver-460 on laptop with hybrid graphics (intel and nvidia). GPU Utilization in Nvidia x server settings will always be 0% when i run apps (for example celluloid) by right clicking and selecting "Run with NVIDIA GPU" but if i run celluloid with following command "__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia celluloid" then the GPU Utilization will go up. So i guess the driver is working properly but the problem is with desktop environment.

**Steps to reproduce**

Right click on apps and select "Run with NVIDIA GPU" 

**Expected behaviour**

GPU Utilization in Nvidia x server settings should go up.

**Comment by mtwebster** [comment]
Stop reposting, cinnamon is enough
