### ISSUE TITLE
Linux Mint 20.2 Uma has broken libpng package

### ISSUE THREAD

**Issue by Sakura0134** [linuxmint/cinnamon-desktop#197]
I believe it's the right place since I cant find Mints source code. Apparantly, there is a bug with Mint Uma preventing it from opening png image. More info can be found here. https://github.com/yuzu-emu/yuzu/issues/6784

**Comment by two-dogs** [comment]
@Sakura0134 the libpng* packages are ubuntu-20.4 specific, i would also hit up ubuntu via issue if they have a github presence

**Comment by Sakura0134** [comment]
Sorry, this is not a bug related to Mint in general
