### ISSUE TITLE
Wallpaper issues

### ISSUE THREAD

**Issue by Citrom67** [linuxmint/cinnamon-desktop#203]
I'm loving cinnamon ever since I switched to it, but I have one current issue that I have not found a solution to anywhere.

After I restart my PC, and even after just logging out and then logging in, my desktop wallpaper **zooms in on my main monitor**, way more than it should in normal condition. On my 2nd monitor it doesn't change from the usual at all, only on my main.
And then I have to switch to some other background scaling mode, and then back to zoom to have it fixed.

One of my friend said that I could make a script for it to fix on log in, but if there is any fix to it without that, I would like to do that!

**_System:_** 
**OS:** _AcroLinux_
**Kernel:** _5.15.12-arch1-1_
**DE:** _Cinnamon 5.1.12_

_**Monitors:**_
**1st:** _1920x1080_
**2nd:** _1024x768_

If I missed any important things I'll answer in comments! But this issue was present back on POP_OS! too when I used cinnamon there.

### After Logging in
![after login](https://user-images.githubusercontent.com/54332606/147749482-39c38fc9-8504-4289-87c5-d83fc3040272.png)

### Normal -- Fixed
![normal](https://user-images.githubusercontent.com/54332606/147749485-e4d119cd-aa8d-4f8f-997a-64876c4f9f65.png)

**Comment by mtwebster** [comment]
Hi, if you change which monitor is your primary (temporarily) does the problem still occur?

**Comment by Citrom67** [comment]
> Hi, if you change which monitor is your primary (temporarily) does the problem still occur?

It still happens even if I set my primary to be another monitor

**Comment by mtwebster** [comment]
How large is the wallpaper? I should be able to duplicate the display configuration.

**Comment by Citrom67** [comment]
I dont remember...
Its one of the default wallpapers of AcroLinux, so I assume it's 4k, but I cant check it today sadly since Im working. 

But it also happened with a normal 1080p picture as well, so as far as I know its not because of the picture resolution

**Comment by Citrom67** [comment]
I just checked and my current wallpaper is 3840x2160,
but as I said it also happened with a normal 1920x1080 wallpaper, which would be the native resolution of my monitor.

**Comment by Cobinja** [comment]
Can you post the contents of your file $HOME/.xsession-errors?

**Comment by Citrom67** [comment]
> Can you post the contents of your file $HOME/.xsession-errors

Well, I don't have any .xsession-erros file, I have only the normal .xsession .xsessionrc

**Comment by Citrom67** [comment]
If I set it to anything other than zoom, it doesn't get zoomed in, but somehow the resolution still looks like it's halved.

I remember that when I installed AcroLinux, then it had a background manager, I don't remember which, but as far as I know, I removed it, and I don't even have anything related to it starting up on log in

**Comment by Citrom67** [comment]
I've written a script to reset it, when I log in, so I guess that a good solution for now.
Tho I'll still try if someone has any idea what can cause it! Thanks for your helps tho

**Comment by Citrom67** [comment]
I've put a script up on my [GitHub repo](https://github.com/Citrom67/dotfiles-scripts/blob/main/Login-Settings.sh) so if anyone has this problem they can use it! But gonna close the issue for now!
