### ISSUE TITLE
GTK3 theme doesn't show in the selection list

### ISSUE THREAD

**Issue by fblais** [linuxmint/cinnamon-desktop#223]
NOTE: not sure which Cinnamon sub-folder to post that issue, so sorry if not the right one.

Hi.
I have compiled a theme which is designed for Gnome DE.
https://github.com/lassekongo83/adw-gtk3
I'm aware there's only GTK code; no Cinnamon or XFCE.
I'd expect to be able to select the GTK theme in the Applications list.
But it's not shown.
Same thing with Mint 20.3 and 21. (different Cinnamon versions)

The theme gets installed in /usr/share/themes.
The theme has an index.theme file, and only a gtk-3.0 folder.
No GTK2 and GTK4.

It works in Gnome, and also XFCE, go figure.
I'm aware that if the GTK theme was available, I'd need to select another theme for the window decorations in Mint 20.3.
But not with Mint 21, I'm aware of that.

You can try it yourself if you want.
You need git, sassc and meson to get the source code and compile it.
Installing meson also installs ninja-build.

In a terminal:
git clone https://github.com/lassekongo83/adw-gtk3
cd adw-gtk3
meson build
sudo ninja -C build install

That's it.
Thanks in advance.
François

**Comment by mtwebster** [comment]
There's a bug in the theme picker.

For now, you can run:
```
sudo mkdir /usr/share/themes/adw-gtk3/gtk-2.0
sudo mkdir /usr/share/themes/adw-gtk3-dark/gtk-2.0
```
and they'll show up.

**Comment by fblais** [comment]
Great, thanks!

**Comment by fblais** [comment]
Thanks Michael.
This will appear in a newer version of Cinnamon next time a build is done I guess.

**Comment by mtwebster** [comment]
Yes - there'll probably be one soon.
