### ISSUE TITLE
"Always on top" shortcut removed??

### ISSUE THREAD

**Issue by paxdriver** [linuxmint/cinnamon-desktop#227]
In Mint 19 I used to be able to ALT+SPACE to pull up the window options, then press "T" to keep the window "Always on Top" but in Mint Cinnamon 21 now the "T" shortcut in that window doesn't work anymore. Not sure why that was changed but it's really annoying to have to use the mouse. As a developer I use that feature a lot so a keyboard combination is ideal, if it's an easy feature to bring back that would be awesome.

Love the work, the project, and the community so thank you!

**Comment by mtwebster** [comment]
Hi, for Cinnamon 5.4 there's an extension you can install to supply this functionality:
![image](https://user-images.githubusercontent.com/262776/206508595-b61d1e6d-11ba-46ec-ab04-c1c3b31dc94c.png)

The shortcuts are restored in Cinnamon 5.6 (the extension is no longer needed).
