### ISSUE TITLE
File dialog loses focus

### ISSUE THREAD

**Issue by kartagis** [linuxmint/cinnamon-desktop#34]
Hi,

On websites where I click on Browse to upload files, the file dialog loses focus, so I can't use the keyboard to type the first letter of the file. I have to use the mouse to click on the name input field first. I am using Linux Mint 17 with Cinnamon. I also have the issue as #1318152, and in addition, the issue I described above. Please the how the dialog title is dimmed (?) in the attachment below.
![screenshot from 2014-12-30 11 55 07](https://cloud.githubusercontent.com/assets/1607518/5577496/0b38ddde-901b-11e4-9fb4-4b19aafd6ffc.png)

**Comment by leigh123linux** [comment]
Closed.

Please move this issue to nemo.

https://github.com/linuxmint/nemo/issues

**Comment by JosephMcc** [comment]
This has nothing to do with Nemo either. That dialog is provided by Gtk.
