### ISSUE TITLE
Tiling improvement

### ISSUE THREAD

**Issue by edmundlaugasson** [linuxmint/cinnamon-desktop#38]
I would propose to improve tiling. Currently there is possible to tile minimal 1/4 of screen. I would propose even half more - this means 1/8 of screen.
Shortcut keys Super+arrow is great - just pressing repeatedly like currently would be great.
This would be useful to be configurable e.g. from Settings->Window menu:
* Maximum window tiling:
  - 1/4 window
  - 1/8 window
This tiling improvement could be useful especially for large screens.

Another improvement would be to keep e.g. ALT pressed while Super is pressed and then moving arrow keys would resize window. Currently there are unassigned shortcut keys to resize vertically and horisontally - I would propose to add Super+ALT+arrow for them. If this is assigned already then choose something similar else.
Possibly there would be useful to get some ideas from i3 window manager - http://i3wm.org/ - how to effectively use screen layout.

**Comment by tp0** [comment]
#4451

**Comment by JosephMcc** [comment]
The Cinnamon issue is close enough and is a better place for it.
