### ISSUE TITLE
[BUG] Cinnamon crashes with big windows

### ISSUE THREAD

**Issue by germanfr** [linuxmint/cinnamon-desktop#57]
Resizing a window much more wider than the screen makes cinnamon crash. I am running Cinnamon version 2.6.13 on Linux Mint 17.2.

I don't know if you already know this but I didn't find any issue here about it.

**Comment by leigh123linux** [comment]
Is this still an issue in cinnamon-3.2.x?, I am sure this issue was fixed in muffin.

If it's still an issue feel free to file a bug against muffin.

https://github.com/linuxmint/muffin/issues

**Comment by germanfr** [comment]
Yes, It was fixed. Thank you.
