### ISSUE TITLE
Add flat pointer profile tick to options please 

### ISSUE THREAD

**Issue by Yanpas** [linuxmint/cinnamon-desktop#60]
Since libinput 1.1 the developers added flat profile. It gives 1:1 mouse movement, i.e. without any acceleration (handy for gamers). You are able to adjust only speed of pointer with this profile
Desripton on the bottom of the page: [http://wayland.freedesktop.org/libinput/doc/latest/pointer-acceleration.html](url)

**Comment by mtwebster** [comment]
Cinnamon does not yet use Wayland or libinput.

**Comment by Yanpas** [comment]
Oh, I thought every distro uses X.org libinput backend. So Cinnamon uses xf86-input-evdev?

I guess Cinnamon will switch to libinput soon, so the report may stay opened. Otherwise I guess it should be closed

**Comment by leigh123linux** [comment]
@Yanpas You will need to open a new issue against cinnamon-settings-daemon which recently had libinput support added.

https://github.com/linuxmint/cinnamon-settings-daemon/issues
