### ISSUE TITLE
gtk-warning after full upgrade arch

### ISSUE THREAD

**Issue by LinArcX** [linuxmint/cinnamon-desktop#61]
hi
after 20 days i decide to update/upgdate my system with delicious:"sudo pacman -Syu"..but..after reboot,all panels and nemo changed .and this is my nemo - q output:

[saeed@saeed ~]$ nemo -q

(nemo:5373): Gtk-WARNING **: Theme parsing error: gtk.css:1581:39: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(nemo:5373): Gtk-WARNING **: Theme parsing error: gtk.css:1581:77: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

(nemo:5373): Gtk-WARNING **: Allocating size to GtkGrid 0x15a42a0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
`

**Comment by JosephMcc** [comment]
This belongs at https://github.com/linuxmint/nemo/issues
Please do a search there and make sure the issue hasn't already been reported.
