### ISSUE TITLE
cannot define 3 or more layers of application in menu

### ISSUE THREAD

**Issue by LinArcX** [linuxmint/cinnamon-desktop#64]
hi
i want to creae 3 layers of application in menu but after define level 2..all apps gather in one place.
look:
![cin1](https://cloud.githubusercontent.com/assets/10884422/15052002/a97035f0-1310-11e6-8427-d91328c03e91.png)

**Comment by JosephMcc** [comment]
This belongs at https://github.com/linuxmint/Cinnamon
