### ISSUE TITLE
Only "File" menu item visible in Gimp menu bar

### ISSUE THREAD

**Issue by Nick-Payne** [linuxmint/cinnamon-desktop#68]
Mint 18 Cinnamon amd64. If I run Gimp from the gimp-edge PPA or build it myself from git master, the Gimp menu bar only shows the 'File' menu item. The other menus (Edit, View, Select, etc) are not visible, but they are actually there, because if I click on the File menu and then use the left arrow on the keyboard, I see each of the other menus drop down as they become active, and I can select any of the menu items and they work as expected.

If I change the Cinnamon System Settings for Themes, Settings, 'Show icons in menus' to OFF, then all items in the Gimp menu bar menu become visible.

**Comment by RavetcoFX** [comment]
This really has nothing to do with cinnamon-desktop or even cinnamon, I would recommend closing this report and filing a bug report with gimp

**Comment by JosephMcc** [comment]
Quote from the ppa launchpad page:
> These packages were built of the development branch of the GIMP. They may be very unstable, and > as such should not be used in production.

**Comment by Nick-Payne** [comment]
> This really has nothing to do with cinnamon-desktop or even cinnamon, I would recommend closing this report and filing a bug report with gimp

I already did - their suggestion: file a ticket in Mint's bugtracker.

The identical Gimp build has no problem with menu items not visible in Ubuntu 16.04.
