### ISSUE TITLE
disappearance of the desktop icons and right click doesn't work after login with root

### ISSUE THREAD

**Issue by Muhammed-Pro** [linuxmint/cinnamon-desktop#75]
Linux Mint 18 "Sarah" x64
after I enabled root login from login window, the desktop icons are disappeared, also right click not work, it's working normaly on another user

![screenshot from 2016-10-03 22-05-00](https://cloud.githubusercontent.com/assets/6201621/19093776/936a3a50-8a5a-11e6-824b-ccc111de87ec.png)

**Comment by leigh123linux** [comment]
From the nemo changelog.

> nemo (2.4.3) rebecca; urgency=medium
> 
>   * Never allow root nemo to manage the desktop.
> 
> -- Clement Lefebvre <root@linuxmint.com> Sat, 22 Nov 2014 17:17:30 +0100

**Comment by Muhammed-Pro** [comment]
@leigh123linux Why it's not allowed ? its working in other linux distribution

**Comment by leigh123linux** [comment]
No reason was given on the commit

https://github.com/linuxmint/nemo/commit/acabbaf6ca8e5ffc29851d766339c602777c4427

@mtwebster  do you remember why?
