### ISSUE TITLE
Menu bar appears in Desktop

### ISSUE THREAD

**Issue by sayyaff** [linuxmint/cinnamon-desktop#76]
![screenshot from 2016-10-12 16-31-36](https://cloud.githubusercontent.com/assets/8475267/19307672/621d53ac-9099-11e6-8e0c-26746bc950ba.png)

For Desktop a menu bar is created. Picture is given in above
This issue can be created by installing OS ubuntu 16.04.1 LTS, cinnamon-desktop-environment and Pantheon desktop environment
- after installing all go to cinnamon desktop environment
- logout cinnamon desktop environment
- log in with Pantheon desktop environment 
- search for file their would be two file appearing open both and one of them would generate cinnamon desktop then logout Pantheon desktop environment 
- log in with cinnamon desktop environment then this occurs

**Comment by leigh123linux** [comment]
Closed.

Please move this issue to nemo as that is responsible for drawing the desktop.

https://github.com/linuxmint/nemo/issues
