### ISSUE TITLE
 [A bug?]desktop icon re-arranged after resolution changed

### ISSUE THREAD

**Issue by highwindmx** [linuxmint/cinnamon-desktop#8]
After the resolution changed(16:9->4:3),the icon on the desktop(especailly those at the corner) get overlapped.

How about at least give us a warning before this happened?
Or the arrangement of icons on desktop use “align center”
![screenshot from 2014-01-28 17 32 47](https://f.cloud.github.com/assets/6413481/2025736/2146d212-8882-11e3-9768-d384f89b996a.png)

**Comment by leigh123linux** [comment]
Closed.

Please move this issue to nemo as that is responsible for drawing the desktop.

https://github.com/linuxmint/nemo/issues
