### ISSUE TITLE
desktop dies immediatly as an USB device is plugged in

### ISSUE THREAD

**Issue by gantsevdenis** [linuxmint/cinnamon-desktop#91]
Mint 18.1 'Serena' Cinnamon 64 bits
Every time I plug a USB device (my phone or USB flash; but USB mouse is ok) in a port (any usb port), my desktop stops working. This happens exactly at the moment when a new popup opens allowing me to explore the device.
I cannot click on any icon or any file in my desktop, however I can still access them through "~home/desktop/whatever.txt". The desktop background picture disappears, it turns black. 
This issue happens always.
Everything else keeps working as usual (the Menu button, the low panel.. all other software and internet work fine).

**Comment by clefebvre** [comment]
We'll need a backtrace for this (the new mintreport tool shipping in Mint 18.3 will help with that), and this is off-topic here.. cinnamon-desktop is a library, not the Cinnamon DE.
