### ISSUE TITLE
Feature request: allow longer 'suspend when inactive' settings

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/cinnamon-desktop#93]
![image](https://cloud.githubusercontent.com/assets/9998846/26656021/dfebc7c8-464c-11e7-814d-23742c0d4db3.png)

I'd like to be able to set the computer to suspend when inactive - and when on AC power - after two hours. (Why? Well, my computer gets a bit hot after a while, but I don't want it to go into a deep sleep after only one hour . . I note that Windows - or at least Windows 8 - offers a wider range of time options than, at present, does Mint.)

Mint 18.1 x64 Cinnamon (3.2.7).

**Comment by blackICE19240** [comment]
If you google around a bit I'm sure it is possible to do this manually just by editing the right text somewhere

**Comment by leigh123linux** [comment]
Issue moved to [linuxmint/cinnamon-settings-daemon #187](https://github.com/linuxmint/cinnamon-settings-daemon/issues/187) via [**ZenHub**](https://www.zenhub.com/)
