### ISSUE TITLE
background desktop wallpaper  gets jumbled up when logging out and back in

### ISSUE THREAD

**Issue by seantum** [linuxmint/cinnamon-desktop#94]
In Cinnamon 18.2 Beta, when I log out and log in again, the desktop wallpaper I've set gets jumbled up. - I then have to choose another wallpaper and then the old one, and everything gets restored.
picture: http://imgur.com/a/tqLFo

and here as it should be (after I set the wallpaper anew): http://imgur.com/a/3Cdz1

**Comment by seantum** [comment]
bump. Anyone an idea?

**Comment by JosephMcc** [comment]
This was an issue when running in VBox that should have been fixed in Muffin quite some time ago.
