### ISSUE TITLE
README file suggests checking INSTALL

### ISSUE THREAD

**Issue by JustJinxed** [linuxmint/cinnamon-desktop#99]
No INSTALL file to read... May want to update the README

"
Installation
============

See the file 'INSTALL'. If you are not using a released version of
cinnamon-desktop (for example, if you checked out the code from git), you
first need to run './autogen.sh'.
"

**Comment by agwells** [comment]
Looks like this line is left over from when Gnome's `README` was copied in the initial fork commit. There has actually **never** been an `INSTALL` file in this repo!

https://github.com/linuxmint/cinnamon-desktop/commit/c189ae10bef6daf80a08519a6891a7601507238c#diff-c47c7c7383225ab55ff591cb59c41e6bR28
